// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Real, minimal document fixtures whose text is extracted by Apache Tika via the
// loader's native extractor. PDF only: the PDF below was generated by PDFBox and
// verified to round-trip through Tika's PDF parser, so `buildDocument` returns an
// `ai:TextDocument` whose content contains the marker text. This loader does not
// support Microsoft Office formats (they are skipped like binaries), so no Office
// fixtures are kept here.

// A valid PDF (PDFBox) whose only text is `PDF_TEXT`.
final readonly & byte[] PDF_BYTES = base64 `JVBERi0xLjYKJfbk/N8KMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovVmVyc2lvbiAvMS42Ci9QYWdlcyAyIDAgUgo+PgplbmRvYmoKNyAwIG9iago8PAovTGVuZ3RoIDYzCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCj4+CnN0cmVhbQ0KeJxzCuHSdzNUMDRSCEnjMjdSMDcwUAhJ4dLwzU/OVghwcVNIyU8uzU3NK1EoSa0o0dNUCMnicg3hAgB6Ew6iDQplbmRzdHJlYW0KZW5kb2JqCjggMCBvYmoKPDwKL0xlbmd0aCAxODcKL1R5cGUgL09ialN0bQovTiA1Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9GaXJzdCAyNwo+PgpzdHJlYW0NCnicVY7dCoJAEIVf5TxB4/qLIEJKEUQQFnQhXpgushC74WrU2zcq9HMxA+ebMzPHhQMPvgsfwosRQAQhQohIIEno/LpL0LHupAXtVWtRerxQoALlZtQDBNL03wk6yFbVmXmidFYOpgqFyz2Kp15Ntl7yrjufokJaM/YNv/AXkBs98NwimvXyYMuQ4/0AwTm/cgkwu+g0XodZTlCAstrKZbKTt4ccVFODNroxrdId6KL0Wlv1AXzwDSMNTM0NCmVuZHN0cmVhbQplbmRvYmoKOSAwIG9iago8PAovTGVuZ3RoIDMzCi9Sb290IDEgMCBSCi9JRCBbPDJCNjNCNTM5MzY2MDE0NTkyNDVCQTYwN0Y4RTRERjNFNTJENUZBNUZEMjBCQTVGQjc1QUNGMjJDRUUzQzE4NTM+IDwyQjYzQjUzOTM2NjAxNDU5MjQ1QkE2MDdGOEU0REYzRTUyRDVGQTVGRDIwQkE1RkI3NUFDRjIyQ0VFM0MxODUzPl0KL1R5cGUgL1hSZWYKL1NpemUgMTAKL0luZGV4IFswIDldCi9XIFsxIDEgMV0KL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtDQp4nGNg+M/Iz8DEAUSMTBxMTBzMTBwsjH4MjNcYACDYAnINCmVuZHN0cmVhbQplbmRvYmoKc3RhcnR4cmVmCjUwNAolJUVPRgo=`;

// The marker text Tika extracts from the PDF fixture above.
const string PDF_TEXT = "Mock PDF document text.";
